name = "EnzymeImplicitAD"
uuid = "e5816cd5-ad56-4b36-a2ea-174ddf69c823"
version = "0.1.2"
authors = ["Tamás K. Papp <tkpapp@gmail.com>"]

[workspace]
projects = ["test"]

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
TrustRegionMethods = "14486370-d344-40f0-8ff9-262f8a3330be"

[compat]
ADTypes = "1.22"
ArgCheck = "2.5"
ConcreteStructs = "0.2.4"
DocStringExtensions = "0.9"
Enzyme = "0.13"
LinearAlgebra = "1.12.0"
OhMyThreads = "0.8.5"
TrustRegionMethods = "0.6.3"
julia = "1.12"
